Importing most important python libraries:

In [123]:
import pandas as pd
import numpy as np

There are 8 different csv files* regarding each year. 
<br>To make full analysis throughout 2015-2022, I am going to join each file into main dataframe using 'for in' loop.

In [124]:
files = ['2015', '2016', '2017', '2018', '2019', '2020', '2021','2022']
          
main_df = pd.DataFrame(pd.read_csv(r"C:/Users/Agata/Documents/GitHub/Happiness-Report/source_files/2015.csv"))
main_df['year'] = '2015'
for i in range(1, len(files)):
    data = pd.read_csv(r"C:/Users/Agata/Documents/GitHub/Happiness-Report/source_files/"+files[i]+r".csv")
    df = pd.DataFrame(data)
    df['year'] = files[i]
    main_df = pd.concat([main_df,df],axis=0)
    main_df = main_df.reset_index(drop=True)
main_df.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),...,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,RANK,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita
0,Switzerland,Western Europe,1.0,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Iceland,Western Europe,2.0,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Denmark,Western Europe,3.0,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Norway,Western Europe,4.0,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Canada,North America,5.0,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [125]:
main_df.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual', 'year', 'Lower Confidence Interval',
       'Upper Confidence Interval', 'Happiness.Rank', 'Happiness.Score',
       'Whisker.high', 'Whisker.low', 'Economy..GDP.per.Capita.',
       'Health..Life.Expectancy.', 'Trust..Government.Corruption.',
       'Dystopia.Residual', 'Overall rank', 'Country or region', 'Score',
       'GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Perceptions of corruption',
       'Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support_', 'Healthy life expectancy_',
       'Freedom to make life choices_', 'Generosity_',
       'Perceptions of corruption_', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual', 'RANK', 'Happiness score', 'Whisker-high',
       'Whisker-low', 'Dystopia (1.83) + residual',
       'Explained by: GDP per capita'],
      dtype='object')

Let's see what the dataframe looks like:

In [126]:
main_df.info()
main_df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1231 entries, 0 to 1230
Data columns (total 57 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     617 non-null    object
 1   Region                                      315 non-null    object
 2   Happiness Rank                              315 non-null    float64
 3   Happiness Score                             315 non-null    float64
 4   Standard Error                              158 non-null    float64
 5   Economy (GDP per Capita)                    315 non-null    float64
 6   Family                                      470 non-null    float64
 7   Health (Life Expectancy)                    315 non-null    float64
 8   Freedom                                     470 non-null    float64
 9   Trust (Government Corruption)               315 non-null    float64
 10  Generosity                                  782 non-null    float64
 11  Dystopia Residual                           315 non-null    float64
 12  year                                        1231 non-null   object
 13  Lower Confidence Interval                   157 non-null    float64
 14  Upper Confidence Interval                   157 non-null    float64
 15  Happiness.Rank                              155 non-null    float64
 16  Happiness.Score                             155 non-null    float64
 17  Whisker.high                                155 non-null    float64
 18  Whisker.low                                 155 non-null    float64
 19  Economy..GDP.per.Capita.                    155 non-null    float64
 20  Health..Life.Expectancy.                    155 non-null    float64
 21  Trust..Government.Corruption.               155 non-null    float64
 22  Dystopia.Residual                           155 non-null    float64
 23  Overall rank                                312 non-null    float64
 24  Country or region                           312 non-null    object
 25  Score                                       312 non-null    float64
 26  GDP per capita                              312 non-null    float64
 27  Social support                              312 non-null    float64
 28  Healthy life expectancy                     312 non-null    float64
 29  Freedom to make life choices                312 non-null    float64
 30  Perceptions of corruption                   311 non-null    float64
 31  Country name                                302 non-null    object
 32  Regional indicator                          302 non-null    object
 33  Ladder score                                302 non-null    float64
 34  Standard error of ladder score              302 non-null    float64
 35  upperwhisker                                302 non-null    float64
 36  lowerwhisker                                302 non-null    float64
 37  Logged GDP per capita                       302 non-null    float64
 38  Social support_                             302 non-null    float64
 39  Healthy life expectancy_                    302 non-null    float64
 40  Freedom to make life choices_               302 non-null    float64
 41  Generosity_                                 302 non-null    float64
 42  Perceptions of corruption_                  302 non-null    float64
 43  Ladder score in Dystopia                    302 non-null    float64
 44  Explained by: Log GDP per capita            302 non-null    float64
 45  Explained by: Social support                448 non-null    float64
 46  Explained by: Healthy life expectancy       448 non-null    float64
 47  Explained by: Freedom to make life choices  448 non-null    float64
 48  Explained by: Generosity                    448 non-null    float64
 49  Explained by: Perceptions of corruption     448 non-null    float64
 50  Dystopia + residual                         302 non-null    float64
 51  RANK                                        147 non-null    float64
 52  Happiness score                             146 non-null    float64
 53  Whisker-high                                146 non-null    float64
 54  Whisker-low                                 146 non-null    float64
 55  Dystopia (1.83) + residual                  146 non-null    float64
 56  Explained by: GDP per capita                146 non-null    float64
dtypes: float64(51), object(6)
memory usage: 548.3+ KB

(1231, 57)

The df has 1231 rows and 56 columns. Let's see how many columns are unique:

In [127]:
len(main_df.columns.unique())

57

All columns are unique. However, the number of columns is high so we will focus on null values next:

In [128]:
main_df.isnull().sum(axis=0)

Country                                        614
Region                                         916
Happiness Rank                                 916
Happiness Score                                916
Standard Error                                1073
Economy (GDP per Capita)                       916
Family                                         761
Health (Life Expectancy)                       916
Freedom                                        761
Trust (Government Corruption)                  916
Generosity                                     449
Dystopia Residual                              916
year                                             0
Lower Confidence Interval                     1074
Upper Confidence Interval                     1074
Happiness.Rank                                1076
Happiness.Score                               1076
Whisker.high                                  1076
Whisker.low                                   1076
Economy..GDP.per.Capita.                      1076
Health..Life.Expectancy.                      1076
Trust..Government.Corruption.                 1076
Dystopia.Residual                             1076
Overall rank                                   919
Country or region                              919
Score                                          919
GDP per capita                                 919
Social support                                 919
Healthy life expectancy                        919
Freedom to make life choices                   919
Perceptions of corruption                      920
Country name                                   929
Regional indicator                             929
Ladder score                                   929
Standard error of ladder score                 929
upperwhisker                                   929
lowerwhisker                                   929
Logged GDP per capita                          929
Social support_                                929
Healthy life expectancy_                       929
Freedom to make life choices_                  929
Generosity_                                    929
Perceptions of corruption_                     929
Ladder score in Dystopia                       929
Explained by: Log GDP per capita               929
Explained by: Social support                   783
Explained by: Healthy life expectancy          783
Explained by: Freedom to make life choices     783
Explained by: Generosity                       783
Explained by: Perceptions of corruption        783
Dystopia + residual                            929
RANK                                          1084
Happiness score                               1085
Whisker-high                                  1085
Whisker-low                                   1085
Dystopia (1.83) + residual                    1085
Explained by: GDP per capita                  1085
dtype: int64

We can see that there are more null values in almost each column than non-null values. That means the columns in each file could be named differently.

In [129]:
main_df.columns.sort_values()

Index(['Country', 'Country name', 'Country or region',
       'Dystopia (1.83) + residual', 'Dystopia + residual',
       'Dystopia Residual', 'Dystopia.Residual', 'Economy (GDP per Capita)',
       'Economy..GDP.per.Capita.',
       'Explained by: Freedom to make life choices',
       'Explained by: GDP per capita', 'Explained by: Generosity',
       'Explained by: Healthy life expectancy',
       'Explained by: Log GDP per capita',
       'Explained by: Perceptions of corruption',
       'Explained by: Social support', 'Family', 'Freedom',
       'Freedom to make life choices', 'Freedom to make life choices_',
       'GDP per capita', 'Generosity', 'Generosity_', 'Happiness Rank',
       'Happiness Score', 'Happiness score', 'Happiness.Rank',
       'Happiness.Score', 'Health (Life Expectancy)',
       'Health..Life.Expectancy.', 'Healthy life expectancy',
       'Healthy life expectancy_', 'Ladder score', 'Ladder score in Dystopia',
       'Logged GDP per capita', 'Lower Confidence Interval', 'Overall rank',
       'Perceptions of corruption', 'Perceptions of corruption_', 'RANK',
       'Region', 'Regional indicator', 'Score', 'Social support',
       'Social support_', 'Standard Error', 'Standard error of ladder score',
       'Trust (Government Corruption)', 'Trust..Government.Corruption.',
       'Upper Confidence Interval', 'Whisker-high', 'Whisker-low',
       'Whisker.high', 'Whisker.low', 'lowerwhisker', 'upperwhisker', 'year'],
      dtype='object')

There is significant redundancy in the columns.
<br>For example, information about countries is split into three columns:
* Country
* Country or region
* Country name
<br> The files have between 9-20 columns. We could equalize the names manually (directly in csv files) which would take long time or create a dictionary with desired names and swap them as below:

In [141]:
correct_names = {'Economy (GDP per Capita)' : 'GDP per Capita',
'Family' : 'Social Support',
'Explained by: Generosity' : "Generosity",
'Health (Life Expectancy)' : 'Healthy Life Expectancy',
'Freedom' : 'Freedom to Make Life Choices',
'Trust (Government Corruption)' : 'Corruption Perception',
'Happiness.Rank' : 'Happiness Rank',
'Happiness.Score' : 'Happiness Score',
'Economy..GDP.per.Capita.' : 'GDP per Capita',
'Health..Life.Expectancy.' : 'Healthy Life Expectancy',
'Trust..Government.Corruption.' : 'Corruption Perception',
'Dystopia.Residual' : 'Dystopia Residual',
'Overall rank' : 'Happiness Rank',
'Country or region' : 'Country',
'Score' : 'Happiness Score',
'GDP per capita' : 'GDP per Capita',
'Country name' : 'Country',
'Regional indicator' : 'Region',
'RANK' : 'Happiness Rank',
'Happiness score' : 'Happiness Score',
'Dystopia (1.83) + residual' : 'Dystopia Residual',
'Ladder score' : 'Happiness Score',
'Dystopia + residual' : 'Dystopia Residual',
'Social support' : 'Social Support',
'Explained by: Social support' : 'Social Support',
'Healthy life expectancy' : 'Healthy Life Expectancy',
'Explained by: Healthy life expectancy' : 'Healthy Life Expectancy',
'Freedom to make life choices' : 'Freedom to Make Life Choices',
'Explained by: Freedom to make life choices' : 'Freedom to Make Life Choices',
'Perceptions of corruption' : 'Corruption Perception',
'Explained by: Perceptions of corruption' : 'Corruption Perception',
'Explained by: Log GDP per capita' : 'GDP per Capita',
'Explained by: GDP per capita' : 'GDP per Capita'
}

In [142]:
main_df = main_df.rename(columns=correct_names)
main_df.columns.sort_values()
main_df.tail()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,GDP per Capita,Social Support,Healthy Life Expectancy,Freedom to Make Life Choices,Corruption Perception,...,Logged GDP per capita,Social support_,Healthy life expectancy_,Freedom to make life choices_,Generosity_,Perceptions of corruption_,Ladder score in Dystopia,Whisker-high,Whisker-low,GDP per Capita
1226,Rwanda*,NaN,143.0,3.268,NaN,NaN,0.000,0.462,0.621,0.544,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.462,3.074,0.001
1227,Zimbabwe,NaN,144.0,2.995,NaN,NaN,0.001,0.270,0.329,0.105,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.110,2.880,0.001
1228,Lebanon,NaN,145.0,2.955,NaN,NaN,0.000,0.631,0.103,0.034,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.049,2.862,1.392
1229,Afghanistan,NaN,146.0,2.404,NaN,NaN,0.000,0.289,0.000,0.005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.469,2.339,0.001
1230,xx,NaN,147.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [143]:
files = ['2015', '2016', '2017', '2018', '2019', '2020','2021','2022']
          
main_df = pd.DataFrame(pd.read_csv(r"C:/Users/Agata/Documents/GitHub/Happiness-Report/source_files/2015.csv"))
main_df = main_df.rename(columns=correct_names)
main_df['Year'] = '2015'

for i in range(1, len(files)):
    data = pd.read_csv(r"C:/Users/Agata/Documents/GitHub/Happiness-Report/source_files/"+files[i]+r".csv")
    df = pd.DataFrame(data)
    df = df.rename(columns=correct_names)
    df['Year'] = files[i]
    main_df = pd.concat([main_df,df],axis=0)
    main_df = main_df.reset_index(drop=True)
    df.to_csv(r"C:/Users/Agata/Documents/"+files[i]+r".csv", index=True)

main_df['Year'] = main_df['Year'].astype(int)
main_df.tail()

#df = pd.DataFrame(pd.read_csv(r"C:/Users/Agata/Documents/GitHub/Happiness-Report/source_files/2016.csv"))
#df = df.rename(columns=correct_names)
#df['Year'] = '2016'
#main_df = pd.concat([main_df,df],axis=0)
#main_df = main_df.reset_index(drop=True)
#main_df =  main_df.set_index(['Year','Country'])
#main_df.to_csv(r"C:/Users/Agata/Documents/"+files[i]+r".csv", index=True)

,Country,Region,Happiness Rank,Happiness Score,Standard Error,GDP per Capita,Social Support,Healthy Life Expectancy,Freedom to Make Life Choices,Corruption Perception,...,lowerwhisker,Logged GDP per capita,Social support_,Healthy life expectancy_,Freedom to make life choices_,Generosity_,Perceptions of corruption_,Ladder score in Dystopia,Whisker-high,Whisker-low
1226,Rwanda*,NaN,143.0,3.268,NaN,0.001,0.000,0.462,0.621,0.544,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.462,3.074
1227,Zimbabwe,NaN,144.0,2.995,NaN,0.001,0.001,0.270,0.329,0.105,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.110,2.880
1228,Lebanon,NaN,145.0,2.955,NaN,1.392,0.000,0.631,0.103,0.034,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.049,2.862
1229,Afghanistan,NaN,146.0,2.404,NaN,0.001,0.000,0.289,0.000,0.005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.469,2.339
1230,xx,NaN,147.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [144]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1231 entries, 0 to 1230
Data columns (total 29 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Country                         1231 non-null   object
 1   Region                          617 non-null    object
 2   Happiness Rank                  929 non-null    float64
 3   Happiness Score                 1230 non-null   float64
 4   Standard Error                  158 non-null    float64
 5   GDP per Capita                  1230 non-null   float64
 6   Social Support                  1230 non-null   float64
 7   Healthy Life Expectancy         1230 non-null   float64
 8   Freedom to Make Life Choices    1230 non-null   float64
 9   Corruption Perception           1229 non-null   float64
 10  Generosity                      1230 non-null   float64
 11  Dystopia Residual               918 non-null    float64
 12  Year                            1231 non-null   int32
 13  Lower Confidence Interval       157 non-null    float64
 14  Upper Confidence Interval       157 non-null    float64
 15  Whisker.high                    155 non-null    float64
 16  Whisker.low                     155 non-null    float64
 17  Standard error of ladder score  302 non-null    float64
 18  upperwhisker                    302 non-null    float64
 19  lowerwhisker                    302 non-null    float64
 20  Logged GDP per capita           302 non-null    float64
 21  Social support_                 302 non-null    float64
 22  Healthy life expectancy_        302 non-null    float64
 23  Freedom to make life choices_   302 non-null    float64
 24  Generosity_                     302 non-null    float64
 25  Perceptions of corruption_      302 non-null    float64
 26  Ladder score in Dystopia        302 non-null    float64
 27  Whisker-high                    146 non-null    float64
 28  Whisker-low                     146 non-null    float64
dtypes: float64(26), int32(1), object(2)
memory usage: 274.2+ KB

In [145]:
df = main_df.loc[:,:'Year']
df = df.drop(columns='Standard Error')
df['Country'] = df['Country'].str.replace('*','')
df[df.Year.isin(['2020','2021'])]
df

C:\Users\Agata\AppData\Local\Temp\ipykernel_11328\677052819.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Country'] = df['Country'].str.replace('*','')

,Country,Region,Happiness Rank,Happiness Score,GDP per Capita,Social Support,Healthy Life Expectancy,Freedom to Make Life Choices,Corruption Perception,Generosity,Dystopia Residual,Year
0,Switzerland,Western Europe,1.0,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015
1,Iceland,Western Europe,2.0,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015
2,Denmark,Western Europe,3.0,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015
3,Norway,Western Europe,4.0,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015
4,Canada,North America,5.0,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
1226,Rwanda,NaN,143.0,3.268,0.00100,0.00000,0.46200,0.62100,0.54400,0.18700,0.00100,2022
1227,Zimbabwe,NaN,144.0,2.995,0.00100,0.00100,0.27000,0.32900,0.10500,0.10600,0.00100,2022
1228,Lebanon,NaN,145.0,2.955,1.39200,0.00000,0.63100,0.10300,0.03400,0.08200,0.00000,2022
1229,Afghanistan,NaN,146.0,2.404,0.00100,0.00000,0.28900,0.00000,0.00500,0.08900,1.26300,2022
1230,xx,NaN,147.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022

In [189]:
df['new_rank'] = df.groupby('Year').rank('dense',ascending=False)

KeyError: 'Year'

In [147]:
df[df.Year.isin(['2016'])]

Empty DataFrame
Columns: [Country, Region, Happiness Rank, Happiness Score, GDP per Capita, Social Support, Healthy Life Expectancy, Freedom to Make Life Choices, Corruption Perception, Generosity, Dystopia Residual, Year]
Index: []

In [148]:
c = df.loc[158:314].Country.tolist()
r = df.loc[158:314].Region.tolist()
region = {c[i] : r[i] for i in range(len(c))}
region
df['Region'] = df.Country.map(region)
df

,Country,Region,Happiness Rank,Happiness Score,GDP per Capita,Social Support,Healthy Life Expectancy,Freedom to Make Life Choices,Corruption Perception,Generosity,Dystopia Residual,Year
0,Switzerland,Western Europe,1.0,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015
1,Iceland,Western Europe,2.0,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015
2,Denmark,Western Europe,3.0,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015
3,Norway,Western Europe,4.0,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015
4,Canada,North America,5.0,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
1226,Rwanda,Sub-Saharan Africa,143.0,3.268,0.00100,0.00000,0.46200,0.62100,0.54400,0.18700,0.00100,2022
1227,Zimbabwe,Sub-Saharan Africa,144.0,2.995,0.00100,0.00100,0.27000,0.32900,0.10500,0.10600,0.00100,2022
1228,Lebanon,Middle East and Northern Africa,145.0,2.955,1.39200,0.00000,0.63100,0.10300,0.03400,0.08200,0.00000,2022
1229,Afghanistan,Southern Asia,146.0,2.404,0.00100,0.00000,0.28900,0.00000,0.00500,0.08900,1.26300,2022
1230,xx,NaN,147.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022

In [149]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1231 entries, 0 to 1230
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Country                       1231 non-null   object
 1   Region                        1180 non-null   object
 2   Happiness Rank                929 non-null    float64
 3   Happiness Score               1230 non-null   float64
 4   GDP per Capita                1230 non-null   float64
 5   Social Support                1230 non-null   float64
 6   Healthy Life Expectancy       1230 non-null   float64
 7   Freedom to Make Life Choices  1230 non-null   float64
 8   Corruption Perception         1229 non-null   float64
 9   Generosity                    1230 non-null   float64
 10  Dystopia Residual             918 non-null    float64
 11  Year                          1231 non-null   int32
dtypes: float64(9), int32(1), object(2)
memory usage: 110.7+ KB

In [150]:
df[df.Year.isin(['2020','2021'])]

Empty DataFrame
Columns: [Country, Region, Happiness Rank, Happiness Score, GDP per Capita, Social Support, Healthy Life Expectancy, Freedom to Make Life Choices, Corruption Perception, Generosity, Dystopia Residual, Year]
Index: []

In [151]:
df.to_csv(r'C:/Users/Agata/Documents/GitHub/Happiness-Report/cleaned_data.csv', index=False)

PermissionError: [Errno 13] Permission denied: 'C:/Users/Agata/Documents/GitHub/Happiness-Report/cleaned_data.csv'